### ISSUE TITLE
Move content from the Racket2 wiki entry to this repository

### ISSUE THREAD

**Issue by jeapostrophe** [racket/racket2-rfcs#26]

**Comment by gus-massa** [comment]
Link for the lazy https://github.com/racket/racket/wiki/Racket2

What is the idea? Move each one to a new issue? Many of them have already been copied. Perhaps we can add a link in the item in the wiki to the issue when it makes sense. It's not a 1-to-1 correspondence, but the first is included in https://github.com/racket/racket2-rfcs/issues/22

Another question: What about minor changes, for example I'd like to force that the last argument of `append` is a `list?` too. I'm worried to have a million of tiny proposals.

**Comment by spdegabrielle** [comment]
@jeapostrophe I'm happy to move each item on https://github.com/racket/racket/wiki/Racket2 to individual issues on https://github.com/racket/racket2-rfcs

Do you think these issues need labels to distinguish the differnet sorts? e.g. 'create an rfc', feature wishlist(form the Racket2 wiki page), and administration issues like this #26 ?

**Comment by spdegabrielle** [comment]
@jeapostrophe I created the ones with known authors:

- The .zo and .dep files should be invisible to the user #32 
- Use syntax parameters in `for` loops for `break` and `continue` instead of keywords #31  
- Make all of `match`’s patterns properly hygienic, rather than inspecting datums for the primitive pattern-matching constructs. #30 
- The values returned by `make-custom-hash-types` and `make-custom-set-types` have a different order. Change one of them to improve consistency. #29  
- Mutable vector should be growable. #28 
- make regexes not need double escaping #27

**Comment by spdegabrielle** [comment]
@jeapostrophe the older entries have been moved to a single issue #33 and the wiki page changed to let contributors know they should use this repo

**Comment by jeapostrophe** [comment]
Thank you! @spdegabrielle

**Comment by spdegabrielle** [comment]
@jeapostrophe if you are happy please close this issue.
kind regards
Stephen
